version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: market
      POSTGRES_PASSWORD: market
      POSTGRES_DB: market
    ports:
      - "5429:5432"

  app:
    image: 'market:latest'
    build:
      context: .
    container_name: market
    depends_on:
      - db
    ports:
      - "8080:8080"

    environment:
      - POSTGRES_USER=market
      - POSTGRES_PASSWORD=market
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/market
      - SPRING_DATASOURCE_USERNAME=market
      - SPRING_DATASOURCE_PASSWORD=market
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create-drop